### ISSUE TITLE
Review the Digital Standards against our project

### ISSUE THREAD

**Issue by PatrickMessierGoC** [sylvainpaq/cannabis-knights#13]

**Comment by PatrickMessierGoC** [comment]
Nidhi and Allan

**Comment by APhillips06** [comment]
Allan has completed 80% of the review.   Expects to complete the task early afternoon.  A document will be provided.

**Comment by nkalia** [comment]
Read through the digital standards; most we are on right track( iterative approach, involve users), a few are built-in our solution by virtue of using Azure cloud, a few need further consideration. I suggest we have another team chat on building in accessibility; security and privacy risks.
