### ISSUE TITLE
Implement bilingual bot

### ISSUE THREAD

**Issue by PatrickMessierGoC** [sylvainpaq/cannabis-knights#6]

**Comment by PatrickMessierGoC** [comment]
Implement French and English bot

**Comment by PatrickMessierGoC** [comment]
Find French implementation of the bot personality
Sylvain and Patrick

**Comment by DrSylvain** [comment]
- The French and English webpages are now ready.
- Patrick revised the French personality.
- The French bot will be added to the French webpage on Thursday or Friday, as soon as Patrick considers that it's ready.
